version: '4.32.0'

services:

  postgres:
    image: postgres:11.13
    container_name: postgres_db_transaction
    volumes:
      - db-store:/var/lib/postgresql/data
    ports:
      - 5434:5432
    environment:
      - POSTGRES_DB=t1_demo_transaction
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
volumes:
  db-store:
    driver: local